require('./node_modules/angular/angular.js')
require('./node_modules/angular-route/angular-route.js')
require('./node_modules/angular-resource/angular-resource.js')
require('./node_modules/angular-animate/angular-animate.js')
require('./node_modules/angular-sanitize/angular-sanitize.js')
require('./node_modules/angular-aria/angular-aria.js')
require('./node_modules/angular-messages/angular-messages.js')